# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 16:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mybackend', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(default='F_1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='NOTE', max_length=20)),
                ('category_name', models.CharField(default='NOTE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.CharField(default=b'2016-12-23 08:27:39', max_length=200)),
                ('patient_id', models.CharField(default='', max_length=100)),
                ('recipients', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('note', models.TextField(blank=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='NoteCategory', to='tracker.NoteCategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGeneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genelist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genelist', to='mybackend.GeneLists')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default=1, max_length=50)),
                ('affected_status', models.CharField(default='UnKnown', max_length=50)),
                ('desc', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPhenoTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Phenotype', max_length=200)),
                ('acc', models.CharField(default='HP:0000000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(default='SELF', max_length=20)),
                ('rel_name', models.CharField(default='Self', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default='', max_length=100)),
                ('epic_order_id', models.CharField(default='', max_length=100)),
                ('order_name', models.CharField(max_length=100, unique=True)),
                ('order_date', models.CharField(default=b'2016-12-23 08:27:39', max_length=50)),
                ('updated', models.CharField(default=b'2016-12-23 08:27:39', max_length=50)),
                ('due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('complete_date', models.CharField(blank=True, default='', max_length=50)),
                ('provider', models.CharField(default='', max_length=200)),
                ('doctor', models.CharField(default='', max_length=200)),
                ('doctor_phone', models.CharField(default='', max_length=50)),
                ('facility', models.CharField(default='', max_length=200)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('physician_phenotype', models.CharField(blank=True, max_length=300, null=True)),
                ('phenotype', models.CharField(blank=True, max_length=300, null=True)),
                ('desc', models.TextField(blank=True)),
                ('flag', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('status_name', models.CharField(max_length=50)),
                ('status_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='SINGLE', max_length=20)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatientFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.CharField(default=b'2016-12-23 08:27:39', max_length=200)),
                ('file_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'Text-PDF'), ('WORD', 'Text-Word'), ('TEXT', 'Text')], default='IMAGE', max_length=10)),
                ('file', models.FileField(blank=True, max_length=400, null=True, upload_to='/Users/s0199669/gcloud/gims/staticfiles/IMAGES/Patient/')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientOrderPhenoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pheno_checklists', models.CharField(blank=True, max_length=400, null=True)),
                ('pheno_valuelists', models.CharField(blank=True, max_length=4000, null=True)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pheno_order', to='tracker.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='PatientOrderPhenoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='', max_length=100)),
                ('relative', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('mrn', models.CharField(max_length=100)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('work_phone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ethnicity', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedigree_json', models.CharField(default='[]', max_length=2000)),
                ('pedigree_image', models.ImageField(blank=True, max_length=400, null=True, upload_to='/Users/s0199669/gcloud/gims/staticfiles/IMAGES/Pedigree/')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(default='', max_length=20)),
                ('rel_name', models.CharField(default='', max_length=100)),
                ('allowed_sex', models.CharField(default='', max_length=20)),
                ('back_relation_female', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='female', to='tracker.PeopleRelations')),
                ('back_relation_male', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='male', to='tracker.PeopleRelations')),
            ],
        ),
        migrations.CreateModel(
            name='PhenoTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=b'2016-12-23 08:27:39', max_length=200)),
                ('name', models.CharField(default='Phenotype', max_length=200)),
                ('type', models.CharField(choices=[('TEXT', 'Text Input'), ('IMAGE', 'Image File'), ('FILE', 'Text / Scan File'), ('ETC', 'ETC'), ('GENELIST', 'Genelists')], default='TEXT', max_length=10)),
                ('desc', models.CharField(default='..', max_length=200)),
                ('image', models.ImageField(blank=True, max_length=400, null=True, upload_to='/Users/s0199669/gcloud/gims/staticfiles/IMAGES/Phenotypes/')),
                ('geno_list', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(default='SELF', max_length=20)),
                ('rel_name', models.CharField(default='Self', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SampleContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('desc', models.CharField(blank=True, default=' ', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='..', max_length=200)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('file_location', models.CharField(default='..', max_length=200)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('loom_id', models.CharField(default='..', max_length=200)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='SampleOrderRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_Status', models.CharField(default='unknown', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Orders')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Relations')),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(max_length=50, unique=True)),
                ('container', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(default='..', max_length=200)),
                ('type', models.CharField(default='..', max_length=200)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('patient_id', models.CharField(default=1, max_length=100)),
                ('name', models.CharField(default='..', max_length=200)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=datetime.datetime(2016, 12, 23, 16, 27, 39, 559754, tzinfo=utc), max_length=50)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Orders')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Samples')),
            ],
        ),
        migrations.AddField(
            model_name='sampleorderrel',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Samples'),
        ),
        migrations.AddField(
            model_name='samplefiles',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Samples'),
        ),
        migrations.AddField(
            model_name='samplecontainer',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Samples'),
        ),
        migrations.AddField(
            model_name='patientrelations',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.PeopleRelations'),
        ),
        migrations.AddField(
            model_name='patientorderphenotype',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Patients'),
        ),
        migrations.AddField(
            model_name='patientorderphenotype',
            name='phenotype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.PhenoTypes'),
        ),
        migrations.AddField(
            model_name='patientfiles',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Patients'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderStatus', to='tracker.OrderStatus'),
        ),
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderType', to='tracker.OrderType'),
        ),
        migrations.AddField(
            model_name='orderphenotypes',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tracker.Orders'),
        ),
        migrations.AddField(
            model_name='ordergroups',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_order', to='tracker.Orders'),
        ),
        migrations.AddField(
            model_name='ordergroups',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.OrderRelations'),
        ),
        migrations.AddField(
            model_name='ordergenelist',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gene_order', to='tracker.Orders'),
        ),
        migrations.AddField(
            model_name='notes',
            name='order',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Orders'),
        ),
        migrations.AddField(
            model_name='notes',
            name='recipient',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='writer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Patients'),
        ),
        migrations.AlterUniqueTogether(
            name='ordergenelist',
            unique_together=set([('order', 'genelist')]),
        ),
    ]
