# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170220_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-02-20 13:32:32', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-02-20 13:32:32', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-02-20 13:32:32', max_length=200),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2017-02-20 13:32:32', max_length=200),
        ),
        migrations.AlterField(
            model_name='samplecontainer',
            name='cid',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampleorderrel',
            name='container',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2017, 2, 20, 21, 32, 32, 742412, tzinfo=utc), max_length=50),
        ),
    ]
