# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170323_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcresults',
            name='result_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-03-27 10:23:24', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'20170327', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-03-27 10:23:24', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-03-27 10:23:24', max_length=200),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='result_json',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
    ]
