# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170220_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborderstatus',
            name='labstatus',
            field=models.CharField(default='COLLECTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='laborderstatus',
            name='status_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-02-21 09:21:36', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='lab_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='LabOrderStatus', to='tracker.LabOrderStatus'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'20170221', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-02-21 09:21:36', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-02-21 09:21:36', max_length=200),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2017-02-21 09:21:36', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2017, 2, 21, 17, 21, 36, 63553, tzinfo=utc), max_length=50),
        ),
    ]
