# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170221_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='COLLECTED', max_length=20)),
                ('status_name', models.CharField(max_length=50)),
                ('status_desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-02-21 10:30:44', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-02-21 10:30:44', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-02-21 10:30:44', max_length=200),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2017-02-21 10:30:45', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2017, 2, 21, 18, 30, 45, 6620, tzinfo=utc), max_length=50),
        ),
    ]
