# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170327_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-03-27 13:30:50', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-03-27 13:30:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-03-27 13:30:50', max_length=200),
        ),
    ]
