# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170221_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SampleStatus', to='tracker.SampleStatus'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-02-21 10:32:50', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-02-21 10:32:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-02-21 10:32:50', max_length=200),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2017-02-21 10:32:50', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2017, 2, 21, 18, 32, 50, 494268, tzinfo=utc), max_length=50),
        ),
    ]
