# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20161109_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='race',
            new_name='ethnicity',
        ),
        migrations.RenameField(
            model_name='samples',
            old_name='number',
            new_name='container',
        ),
        migrations.AddField(
            model_name='orders',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='work_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sampleorderrel',
            name='affected_Status',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='samples',
            name='collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-11 09:47:54', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-11 09:47:54', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-11 09:47:54', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 17, 47, 54, 358529, tzinfo=utc), max_length=50),
        ),
    ]
