# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170327_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_account_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_visit_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-03-28 08:22:27', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'20170328', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-03-28 08:22:27', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-03-28 08:22:27', max_length=200),
        ),
    ]
