# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20170329_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2017-03-29 10:35:13', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2017-03-29 10:35:13', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='update_time',
            field=models.CharField(default=b'2017-03-29 10:35:13', max_length=200),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ethnicity',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
