# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20161111_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phenotype',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-11 13:31:23', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-11 13:31:23', max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-11 13:31:23', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 11, 21, 31, 23, 538813, tzinfo=utc), max_length=50),
        ),
    ]
