# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20161111_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigree',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='pedigree',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Patients'),
        ),
        migrations.AddField(
            model_name='pedigree',
            name='pedigree_image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='/Users/s0199669/gcloud/gims/staticfiles/IMAGES/Pedigree/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-15 08:55:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phenotype',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-15 08:55:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='pedigree_json',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-15 08:55:02', max_length=200),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='/Users/s0199669/gcloud/gims/staticfiles/IMAGES/Phenotypes/'),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 16, 55, 2, 340845, tzinfo=utc), max_length=50),
        ),
    ]
