# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20161115_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samples',
            name='desc',
        ),
        migrations.AddField(
            model_name='orders',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samples',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-15 09:25:28', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-15 09:25:28', max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-15 09:25:28', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 17, 25, 28, 269519, tzinfo=utc), max_length=50),
        ),
    ]
