# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20161115_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecategory',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='notecategory',
            old_name='type_name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-15 14:23:25', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-15 14:23:25', max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-15 14:23:25', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 22, 23, 25, 864478, tzinfo=utc), max_length=50),
        ),
    ]
