# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_auto_20161117_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='note',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='samples',
            old_name='note',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2016-11-17 14:01:53', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-17 14:01:53', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-17 14:01:53', max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-17 14:01:53', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 17, 22, 1, 53, 805580, tzinfo=utc), max_length=50),
        ),
    ]
