# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_auto_20161117_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='patient',
        ),
        migrations.AddField(
            model_name='notes',
            name='patient_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2016-11-17 15:04:50', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-17 15:04:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-17 15:04:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-17 15:04:50', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 17, 23, 4, 50, 296859, tzinfo=utc), max_length=50),
        ),
    ]
