# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_auto_20161117_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default=1, max_length=100)),
                ('relative', models.CharField(default=1, max_length=100)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Relations')),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2016-11-18 10:53:33', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-18 10:53:33', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-18 10:53:33', max_length=50),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-18 10:53:33', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 18, 18, 53, 33, 135585, tzinfo=utc), max_length=50),
        ),
    ]
