# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 19:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20161118_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2016-11-18 11:22:12', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-18 11:22:12', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-18 11:22:12', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientrelations',
            name='main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='tracker.Patients'),
        ),
        migrations.AlterField(
            model_name='patientrelations',
            name='relative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='tracker.Patients'),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-18 11:22:12', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 18, 19, 22, 12, 842888, tzinfo=utc), max_length=50),
        ),
    ]
