# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_auto_20161118_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2016-11-18 11:33:18', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-18 11:33:18', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-18 11:33:18', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientrelations',
            name='main',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrelations',
            name='relative',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-18 11:33:18', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 18, 19, 33, 18, 107134, tzinfo=utc), max_length=50),
        ),
    ]
