# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_auto_20161118_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(default='', max_length=20)),
                ('rel_name', models.CharField(default='', max_length=100)),
                ('back_relation_female', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='female', to='tracker.PeopleRelations')),
                ('back_relation_male', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='male', to='tracker.PeopleRelations')),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='update_time',
            field=models.CharField(default=b'2016-11-18 13:21:19', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.CharField(default=b'2016-11-18 13:21:19', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.CharField(default=b'2016-11-18 13:21:19', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientrelations',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.PeopleRelations'),
        ),
        migrations.AlterField(
            model_name='phenotypes',
            name='date',
            field=models.CharField(default=b'2016-11-18 13:21:19', max_length=200),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 11, 18, 21, 21, 19, 136464, tzinfo=utc), max_length=50),
        ),
    ]
