# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=5, null=True)),
                ('aid', models.CharField(max_length=20)),
                ('start_pos', models.CharField(max_length=20, null=True)),
                ('end_pos', models.CharField(max_length=20, null=True)),
                ('allele_1', models.CharField(max_length=200, null=True)),
                ('allele_2', models.CharField(max_length=200, null=True)),
                ('platform_labels', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, null=True)),
                ('cid', models.CharField(max_length=5, null=True)),
                ('offset', models.CharField(max_length=20, null=True)),
                ('data', models.TextField(null=True)),
                ('links', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenomeSnpMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttm_index', models.CharField(max_length=10)),
                ('ref', models.CharField(max_length=200)),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genotypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele1', models.CharField(default='-', max_length=5)),
                ('allele2', models.CharField(default='-', max_length=5)),
                ('genotyped', models.BooleanField(default=True)),
                ('no_calls', models.BooleanField(default=True)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twothreeandme.Accessions')),
            ],
        ),
        migrations.CreateModel(
            name='GenotypesV1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('alleles', django_mysql.models.JSONField(default=dict)),
                ('result_json', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_id', models.CharField(max_length=100, null=True)),
                ('account_id', models.CharField(max_length=100, null=True)),
                ('gene_version', models.CharField(default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('positions', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('request_header', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('response', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genotypesv1',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twothreeandme.Patients'),
        ),
        migrations.AddField(
            model_name='genotypes',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twothreeandme.Patients'),
        ),
    ]
