# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('twothreeandme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotypesv1',
            name='data_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='pre_score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genotypesv1',
            name='alleles',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='genotypesv1',
            name='result_json',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
    ]
