# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCloudFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('obj_type', models.CharField(default='', max_length=50)),
                ('obj_id', models.CharField(default='', max_length=50)),
                ('file_type', models.CharField(default='', max_length=50)),
                ('file_path', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=200, null=True)),
                ('upload_date', models.CharField(default=b'2017-02-17 11:46:03', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='..', max_length=50)),
                ('display_name', models.CharField(default='..', max_length=200)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeneLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='..', max_length=50)),
                ('list', models.TextField(default='..')),
                ('desc', models.CharField(default='..', max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gene_categroy', to='mybackend.GeneCategory')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='..', max_length=50)),
                ('display_name', models.CharField(default='..', max_length=200)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='..', max_length=200)),
                ('desc', models.CharField(default='..', max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_category', to='mybackend.HistoryCategory')),
            ],
        ),
        migrations.CreateModel(
            name='InputTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='text', max_length=200)),
                ('desc', models.CharField(default='..', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MiscMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='..', max_length=200)),
                ('type', models.CharField(choices=[('text', 'text'), ('file', 'file'), ('html', 'html text')], default='text', max_length=200)),
                ('content', models.CharField(default='..', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PhenoTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='..', max_length=50)),
                ('display_name', models.CharField(default='..', max_length=200)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PhenoTypeLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='..', max_length=200)),
                ('desc', models.CharField(default='..', max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pheno_categroy', to='mybackend.PhenoTypeCategory')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pheno_type', to='mybackend.InputTypes')),
            ],
        ),
        migrations.CreateModel(
            name='PhenoTypeListsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='text', max_length=200)),
                ('desc', models.CharField(default='..', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SaveTempdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='json', max_length=200)),
                ('name', models.CharField(default='..', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('data', models.CharField(default='[]', max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='historylists',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_type', to='mybackend.InputTypes'),
        ),
    ]
