# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabWorkFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.CharField(default=b'2016-12-23 08:29:52', max_length=50)),
                ('update_date', models.CharField(default=b'2016-12-23 08:29:52', max_length=50)),
                ('type', models.CharField(max_length=100, null=True)),
                ('samples_list', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabWorkFlowStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('status_name', models.CharField(default='new lab work created', max_length=50)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1', max_length=20)),
                ('workflow_id', models.CharField(max_length=200)),
                ('inputs', models.CharField(blank=True, max_length=400, null=True)),
                ('fixed_inputs', models.CharField(blank=True, max_length=400, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In Active')], default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('type_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In Active')], default='A', max_length=10)),
            ],
            managers=[
                ('wf_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='workflows',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.WorkflowType'),
        ),
        migrations.AddField(
            model_name='labworkflows',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.LabWorkFlowStatus'),
        ),
    ]
