# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170327_1330'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflows',
            name='order_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.OrderType'),
        ),
        migrations.AlterField(
            model_name='labworkflows',
            name='created_date',
            field=models.CharField(default=b'2017-03-27 13:30:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='labworkflows',
            name='updated_date',
            field=models.CharField(default=b'2017-03-27 13:30:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
