# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20170327_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labworkflows',
            name='created_date',
            field=models.CharField(default=b'2017-03-30 14:23:06', max_length=50),
        ),
        migrations.AlterField(
            model_name='labworkflows',
            name='updated_date',
            field=models.CharField(default=b'2017-03-30 14:23:06', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.OrderType'),
        ),
    ]
